Add model based on Efficient Net
Birdovisco/BirdDetect-NeuralNetwork pull request #22
Opened 2024-12-29 18:14 UTC by Cellmer

2024-12-29 19:46 UTC, gitesthuman commented
That is some pretty high accuracy! 😮

2024-12-29 19:50 UTC, gitesthuman requested changes
Could you predict a few examples and write the average inference time in the comment?

2024-12-30 08:37 UTC, Cellmer commented
> Could you predict a few examples and write the average inference time in the comment?

I've added code measuring inference time across 1000 random samples. It's just inference time without data preprocessing. Average inference time is 0.027194 seconds.

2024-12-30 09:22 UTC, gitesthuman approved these changes

2024-12-30 09:25 UTC, merged